export const IS_MODAL_LOGIN_WINDOW_ACTIVE = 'socialNetwork/modalLoginWindow/IS_MODAL_LOGIN_WINDOW_ACTIVE';
export const IS_MODAL_LOGIN_WINDOW_BUTTON_CLICKED = 'socialNetwork/modalLoginWindow/IS_MODAL_LOGIN_WINDOW_BUTTON_CLICKED';
export const SET_CAPTCHA_INTO_STATE = 'socialNetwork/modalLoginWindow/SET_CAPTCHA_INTO_STATE';
export const SET_RESPONSE_ERROR_TEXT_INTO_STATE = 'socialNetwork/modalLoginWindow/SET_RESPONSE_ERROR_TEXT_INTO_STATE';
export const TOOGLE_IS_LOGIN_REQUIREMENT = 'socialNetwork/modalLoginWindow/TOOGLE_IS_LOGIN_REQUIREMENT';